;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ace-jump-mode
	backward-delete-word
	cua--prefix-override-handler
	cua-exchange-point-and-mark
	cua-paste
	org-backward-sentence
	org-ctrl-c-ctrl-c
	org-force-self-insert
	org-forward-sentence
	org-metaleft
	org-metaright
	org-self-insert-command
	org-shiftright
	))

(setq mc/cmds-to-run-once
      '(
	delete-window
	my-jump-to-next
	my-jump-to-prev
	org-cycle
	))
